name: short_project_1
dependencies:
- python=3.8
- pip
- pip:
  - numpy
  - matplotlib
  - brian2
  - sympy==1.4
  - jupyter
  - jupyterlab
  - scipy
  - seaborn
  - scikit-learn
  - pandas
- pyaudio
